language: emacs-lisp
before_install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
env:
  - EMACS=emacs24
script:
  cask exec ert-runner